os: linux
language: java
jdk:
  - openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: skip
script:
  - ./gradlew clean build --parallel --no-daemon --build-cache --configure-on-demand
  - ./gradlew jacocoTestReport sonarqube --no-daemon --configure-on-demand